seatable/seatable-plugin-tree

.eslintrc.json
src/app.tsx
src/components/custom-components/index.tsx
src/components/template-components/Header/index.tsx
src/components/template-components/LanguageDropDown/index.tsx
src/components/template-components/PluginPresets/index.tsx
src/components/template-components/PluginSettings/index.tsx
src/hooks/useClickOut.tsx
src/model/preset.ts
src/plugin-config/info.json
src/utils/custom-utils/utils.ts
src/utils/template-utils/interfaces/PluginPresets/Item.interface.ts
src/utils/template-utils/utils.ts

Fixed issues about `any` rule. 
Any should be avoided as much as possible, when it is not then it's better to add an eslint line and skip the `any`

Starting to fix any issues

---

src/components/template-components/PluginSettings/index.tsx

I believe the fix for this was already in the source code but commented out. Please test if it also works on your end

Reset new value of level dropdowns on level change

---

src/components/custom-components/index.tsx
src/components/template-components/PluginSettings/index.tsx

Handling Level Selections

---

src/app.tsx
src/components/custom-components/ExpandableItem/index.tsx
src/components/custom-components/index.tsx
src/index.js
src/styles/template-styles/Plugin.module.scss
src/utils/custom-utils/interfaces/CustomPlugin.ts
src/utils/custom-utils/utils.ts

Issue #17 
No visible change on dev. Seems to work on production but the plugin closes (don't know if this is a major issue)
https://github.com/seatable/seatable-plugin-tree-list/assets/69858244/54075ce1-d313-4f7c-88ea-37f4e32211cc

PTL-017: add new row to appropriate level table

---

src/utils/custom-utils/utils.ts

Issue with rendering third rows

---

src/app.tsx
src/components/template-components/PluginSettings/index.tsx

fix second level headrow name

---

src/components/custom-components/index.tsx
src/components/template-components/PluginSettings/index.tsx
src/locale/lang/en.json
src/styles/template-styles/PluginSettings.module.scss

Change disable btns position

---

src/styles/custom-styles/CustomPlugin.module.scss
src/styles/template-styles/PluginPresets.module.scss
src/styles/template-styles/formatter/Formatter.module.scss
src/utils/template-utils/constants/index.ts

Issue #83 
- Title does not break now
- If column width is small, overflow scroll applied

(UI) #83 - add text nowrap and overflow scroll to column titles

---

src/components/custom-components/ExpandableItem/index.tsx
src/components/custom-components/index.tsx
src/styles/template-styles/PluginPresets.module.scss
src/styles/template-styles/formatter/Formatter.module.scss
src/utils/custom-utils/interfaces/CustomPlugin.ts
src/utils/template-utils/constants/index.ts

fix min width of each rows on expand

---

src/app.tsx
src/components/custom-components/ExpandableItem/index.tsx
src/styles/template-styles/Plugin.module.scss

add scrollbar and remove repeated row values

---

src/components/custom-components/ExpandableItem/index.tsx
src/components/custom-components/index.tsx
src/components/template-components/Elements/Formatter/LinkFormatter.tsx
src/utils/custom-utils/utils.ts

Crash issues

---

src/app.tsx
src/components/custom-components/index.tsx
src/utils/custom-utils/interfaces/CustomPlugin.ts

PTL: Issue #103

---

src/components/custom-components/ExpandableItem/index.tsx
src/components/custom-components/index.tsx
src/components/template-components/Elements/Formatter/index.tsx
src/styles/custom-styles/CustomPlugin.module.scss

fix first column data formatting

---

src/components/template-components/Header/index.tsx

Remove Download

---

src/components/template-components/Elements/Formatter/ImageFormatter.tsx
src/components/template-components/Elements/Formatter/index.tsx
src/components/template-components/Header/index.tsx
src/styles/template-styles/formatter/Formatter.module.scss
src/styles/template-styles/formatter/ImageFormatter.module.scss

fix images preview

---

src/app.tsx

fix plugin height to display scrollbar

---

src/app.tsx
src/components/template-components/PluginSettings/index.tsx
src/utils/template-utils/interfaces/PluginSettings.interface.ts

update activelevelselections on dropdown select

---

src/app.tsx
src/components/custom-components/HeaderRow/index.tsx
src/components/custom-components/index.tsx
src/components/template-components/Elements/Formatter/Editors/ImageEditor/image-previewer-lightbox.jsx
src/components/template-components/Elements/Formatter/Editors/SingleSelect/single-select-editor.jsx
src/components/template-components/Elements/Formatter/ImageFormatter.tsx
src/components/template-components/PluginSettings/index.tsx
src/styles/custom-styles/CustomPlugin.module.scss
src/utils/custom-utils/utils.ts
src/utils/template-utils/constants/index.ts
src/utils/template-utils/interfaces/PluginSettings.interface.ts

Fix preset settings bug when table is deleted

---

src/components/template-components/Elements/Formatter/CollaboratorFormatter.tsx
src/styles/template-styles/Plugin.module.scss
src/styles/template-styles/formatter/Formatter.module.scss

Margin Bottom for p

---

src/components/custom-components/HeaderRow/index.tsx

Removing column with Table Name

---

src/app.tsx
src/components/custom-components/HeaderRow/index.tsx
src/components/template-components/PluginSettings/index.tsx
src/utils/custom-utils/constants/index.ts

fix plugin view and third level selection

---

src/components/custom-components/index.tsx
src/components/template-components/PluginSettings/index.tsx

show table rows when plugin opens initially

---

src/components/custom-components/HeaderRow/index.tsx
src/components/custom-components/ResizableCell/index.tsx
src/styles/custom-styles/CustomPlugin.module.scss

Adding Icon to Columns

---

src/app.tsx
src/components/template-components/PluginPresets/index.tsx
src/utils/template-utils/utils.ts

Issue #165 
Bug created from Issue #144

update activePresetId on preset name change

---

src/components/template-components/PluginSettings/index.tsx

View Change on useEffect

---

src/components/template-components/PluginPresets/index.tsx
src/utils/custom-utils/utils.ts

Issue #171 
Already on demo, please proceed to test on there as well

reset plugin content on new preset
